### ISSUE TITLE
Project will not run?

### ISSUE THREAD

**Issue by UglyNora** [profwpollock/COP-2805C-2019#1]
Directions followed exactly using ItellijIDEA. Code will not compile. There are several SayHello files listed under SRC>main>java>mypkg>SayHello.java  that contain what looks like Git related items. Should these be deleted first? If I go to the SayHello.java located under the README.md it contains just the java code...???

**Comment by SamGraham34** [comment]
Had the same problem using NetBeans.  It should work now.  See comments on my commit for details.  If I deleted something I shouldn't have, I'm sure he will point it out to everyone on Tuesday.  Code will compile.  You may have to Fetch the new commits to merge with your local repo.

**Comment by profwpollock** [comment]
You're right, there should have been only one SayHello, but some student messed up the repo.  All part of the learning process.  This is closed as "WONTFIX".
